name: auto assign new issue

on:
  issues:
    types: [opened]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v1.11
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'jwonyLee,Aileen-HyunjiSong,getBingsoo,jeffoio,seonyoung169,kartmon61'
